select * from FIRST_HALF 
left join ICECREAM_INFO on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR 
where FIRST_HALF.TOTAL_ORDER > 3000 and ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' 
order by FIRST_HALF.TOTAL_ORDER DESC;